$source = "/Volumes/data/ld100/Projects/personal/photoshit/source"
$destination = "/Volumes/data/ld100/Projects/personal/photoshit/destination"
#$watermark_text = "travelfreak.ru"
$watermark_text = "© Alexander Lockshyn | travelfreak.ru"
#$watermark_text = "emotionalphoto.com"